version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${SERVER_PORT:-8080}:8080"
      - "${SERVER_MOCK_SERVER_PORT:-8088}:8088"
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=${DB_USER:-eff}
      - DB_PASSWORD=${DB_PASSWORD:-effeModel123}
      - DB_NAME=${DB_NAME:-music_library}
      - DATABASE_URL=postgres://${DB_USER:-eff}:${DB_PASSWORD:-effeModel123}@postgres:5432/${DB_NAME:-music_library}
      - SERVER_PORT=${SERVER_PORT:-8080}
      - SERVER_MOCK_SERVER_PORT=${SERVER_MOCK_SERVER_PORT:-8088}
      - EXTERNAL_API_BASE_URL=http://localhost:${SERVER_MOCK_SERVER_PORT:-8088}
      - EXTERNAL_API_INFO_PATH=${EXTERNAL_API_INFO_PATH:-/info}
    depends_on:
      - postgres
    restart: unless-stopped
    networks:
      - music-network

  postgres:
    image: postgres:latest
    ports:
      - "${DB_PORT:-5432}:5432"
    environment:
      - POSTGRES_USER=${DB_USER:-eff}
      - POSTGRES_PASSWORD=${DB_PASSWORD:-effeModel123}
      - POSTGRES_DB=${DB_NAME:-music_library}
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - music-network

networks:
  music-network:
    driver: bridge

volumes:
  postgres-data: